from setuptools import setup, find_packages

setup(
    name="autocore",
    version="1.3",
    author="Ash",
    url="https://github.com/AshAutomates/AutoCore",
    description="Automate Core Actions",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=[
        "opencv-python",
        "numpy<2",
        "Pillow",
        "pyautogui",
        "pyperclip",
        "easyocr",
        "beautifulsoup4",
        "selenium",
        "webdriver-manager",
        "pywin32; sys_platform == 'win32'",
        "PyPDF2",
        "python-docx",
        "openpyxl",
        "python-pptx",
        "ebooklib",
        "odfpy",
        "extract-msg",
        "striprtf",
        "undetected-chromedriver",
        "requests",
        "pyyaml",
    ],
)
